package com.bocsoft.sqleditor.metadata;

import com.bocsoft.sqleditor.auth.AuthContext;import com.bocsoft.sqleditor.common.ApiException;import com.bocsoft.sqleditor.datasource.SavedDataSource;import com.bocsoft.sqleditor.datasource.TargetConnectionProvider;import com.bocsoft.sqleditor.datasource.api.CursorPage;import com.bocsoft.sqleditor.datasource.connection.ConnectionUse;import com.bocsoft.sqleditor.execution.JdbcTypeNames;import com.bocsoft.sqleditor.metadata.api.*;
import java.sql.*;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;

@Service
public class MysqlMetadataService {
    private static final Set<String>SYSTEM=new HashSet<String>(Arrays.asList("information_schema","performance_schema","mysql","sys"));
    private final TargetConnectionProvider targets;private final MetadataCursorCodec cursors;
    public MysqlMetadataService(TargetConnectionProvider targets,MetadataCursorCodec cursors){this.targets=targets;this.cursors=cursors;}
    public CursorPage<DatabaseItem> databases(AuthContext auth,String id,String keyword,int pageSize,String token,boolean includeSystem){
        if(pageSize<1||pageSize>200)throw ApiException.validation("pageSize","OUT_OF_RANGE","每页数量必须在 1 到 200 之间");String q=normalize(keyword);String scope=id+"|db|"+q+"|"+includeSystem+"|"+pageSize;String after=cursors.decode(token,scope);SavedDataSource source=targets.require(auth,id);
        List<DatabaseItem> all=jdbc(source,c->{List<DatabaseItem> out=new ArrayList<DatabaseItem>();try(ResultSet rs=c.getMetaData().getCatalogs()){while(rs.next()){String name=rs.getString(1);if((includeSystem||!SYSTEM.contains(name.toLowerCase(Locale.ROOT)))&&contains(name,q))out.add(new DatabaseItem(name));}}out.sort(Comparator.comparing(DatabaseItem::getName,String.CASE_INSENSITIVE_ORDER));return out;});return page(all,pageSize,after,scope,item->item.getName());
    }
    public CursorPage<TableItem> tables(AuthContext auth,String id,String database,String keyword,String types,int pageSize,String token){
        validateIdentifier("database",database);if(pageSize<1||pageSize>200)throw ApiException.validation("pageSize","OUT_OF_RANGE","每页数量必须在 1 到 200 之间");String q=normalize(keyword);String[] accepted=parseTypes(types);String scope=id+"|tables|"+database+"|"+q+"|"+String.join(",",accepted)+"|"+pageSize;String after=cursors.decode(token,scope);SavedDataSource source=targets.require(auth,id);List<TableItem> all=jdbc(source,c->{ensureDatabase(c,database);List<TableItem>out=new ArrayList<TableItem>();try(ResultSet rs=c.getMetaData().getTables(database,null,"%",accepted)){while(rs.next()){String name=rs.getString("TABLE_NAME");if(contains(name,q))out.add(new TableItem(database,name,normalizeTableType(rs.getString("TABLE_TYPE")),rs.getString("REMARKS")));}}out.sort(Comparator.comparing(TableItem::getName,String.CASE_INSENSITIVE_ORDER));return out;});return page(all,pageSize,after,scope,item->item.getName());
    }
    public TableDetailResponse detail(AuthContext auth,String id,String database,String table){validateIdentifier("database",database);validateIdentifier("table",table);SavedDataSource source=targets.require(auth,id);return jdbc(source,c->{ensureDatabase(c,database);DatabaseMetaData meta=c.getMetaData();Map<Short,String>pkOrder=new TreeMap<Short,String>();String pkName=null;try(ResultSet rs=meta.getPrimaryKeys(database,null,table)){while(rs.next()){pkName=rs.getString("PK_NAME");pkOrder.put(rs.getShort("KEY_SEQ"),rs.getString("COLUMN_NAME"));}}Set<String>pkSet=new HashSet<String>(pkOrder.values());List<ColumnItem>columns=new ArrayList<ColumnItem>();try(ResultSet rs=meta.getColumns(database,null,table,"%")){while(rs.next())columns.add(new ColumnItem(rs.getString("COLUMN_NAME"),rs.getString("TYPE_NAME"),JdbcTypeNames.name(rs.getInt("DATA_TYPE")),integer(rs,"COLUMN_SIZE"),integer(rs,"COLUMN_SIZE"),integer(rs,"DECIMAL_DIGITS"),rs.getInt("NULLABLE")!=DatabaseMetaData.columnNoNulls,rs.getString("COLUMN_DEF"),rs.getString("IS_AUTOINCREMENT"),rs.getString("REMARKS"),integer(rs,"ORDINAL_POSITION"),pkSet.contains(rs.getString("COLUMN_NAME"))));}if(columns.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"TABLE_NOT_FOUND","表不存在或已不可见");Map<String,IndexAccumulator> idx=new LinkedHashMap<String,IndexAccumulator>();try(ResultSet rs=meta.getIndexInfo(database,null,table,false,false)){while(rs.next()){String name=rs.getString("INDEX_NAME"),column=rs.getString("COLUMN_NAME");if(name==null||column==null)continue;IndexAccumulator a=idx.get(name);if(a==null){a=new IndexAccumulator(name,!rs.getBoolean("NON_UNIQUE"),indexType(rs.getShort("TYPE")));idx.put(name,a);}a.columns.put(rs.getShort("ORDINAL_POSITION"),column);}}List<IndexItem>indexes=new ArrayList<IndexItem>();for(IndexAccumulator a:idx.values())indexes.add(new IndexItem(a.name,a.unique,a.type,new ArrayList<String>(a.columns.values())));return new TableDetailResponse(database,table,columns,pkOrder.isEmpty()?null:new PrimaryKeyItem(pkName,new ArrayList<String>(pkOrder.values())),indexes,readDdl(c,database,table));});}
    private <T>T jdbc(SavedDataSource source,ConnectionUse.Work<T> work){try{return ConnectionUse.execute(targets.borrow(source),source.getDefaultDatabase(),work);}catch(ApiException e){throw e;}catch(SQLException e){throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"METADATA_QUERY_FAILED",safe(e));}}
    private void ensureDatabase(Connection c,String database)throws SQLException{try(ResultSet rs=c.getMetaData().getCatalogs()){while(rs.next())if(database.equals(rs.getString(1))){c.setCatalog(database);return;}}throw new ApiException(HttpStatus.NOT_FOUND,"DATABASE_NOT_FOUND","数据库不存在或已不可见");}
    private <T>CursorPage<T> page(List<T>all,int size,String after,String scope,Name<T>name){int start=0;if(after!=null){while(start<all.size()&&name.get(all.get(start)).compareToIgnoreCase(after)<=0)start++;}int end=Math.min(all.size(),start+size);List<T>items=new ArrayList<T>(all.subList(start,end));String next=end<all.size()&&!items.isEmpty()?cursors.encode(name.get(items.get(items.size()-1)),scope):null;return new CursorPage<T>(items,next);}
    private String[] parseTypes(String raw){String v=raw==null?"TABLE,VIEW":raw;LinkedHashSet<String>out=new LinkedHashSet<String>();for(String x:v.split(",")){String t=x.trim().toUpperCase(Locale.ROOT);if("TABLE".equals(t))out.add("TABLE");else if("VIEW".equals(t))out.add("VIEW");else throw ApiException.validation("types","INVALID","仅支持 TABLE 和 VIEW");}if(out.isEmpty())throw ApiException.validation("types","REQUIRED","至少选择一种对象类型");return out.toArray(new String[0]);}
    private String normalizeTableType(String v){return v!=null&&v.toUpperCase(Locale.ROOT).contains("VIEW")?"VIEW":"TABLE";}private String indexType(short v){switch(v){case DatabaseMetaData.tableIndexClustered:return"CLUSTERED";case DatabaseMetaData.tableIndexHashed:return"HASHED";case DatabaseMetaData.tableIndexStatistic:return"STATISTIC";default:return"OTHER";}}private Integer integer(ResultSet rs,String name)throws SQLException{int v=rs.getInt(name);return rs.wasNull()?null:v;}private String normalize(String v){String q=v==null?"":v.trim();if(q.length()>200)throw ApiException.validation("keyword","OUT_OF_RANGE","关键词最多 200 个字符");return q;}private boolean contains(String v,String q){return q.isEmpty()||v.toLowerCase(Locale.ROOT).contains(q.toLowerCase(Locale.ROOT));}private void validateIdentifier(String field,String value){if(value==null||value.trim().isEmpty()||value.length()>64||value.indexOf('\0')>=0)throw ApiException.validation(field,"INVALID","数据库标识符不合法");}
    private String quoteIdentifier(String value){return "`"+value.replace("`","``")+"`";}
    private String readDdl(Connection c,String database,String table){try(Statement st=c.createStatement();ResultSet rs=st.executeQuery("SHOW CREATE TABLE "+quoteIdentifier(database)+"."+quoteIdentifier(table))){if(rs.next())return rs.getString(2);}catch(SQLException ignored){}return null;}
    private String safe(SQLException e){String m=e.getMessage();return m==null?"元数据查询失败":(m.length()>500?m.substring(0,500):m);}private interface Name<T>{String get(T value);}private static class IndexAccumulator{final String name,type;final boolean unique;final Map<Short,String>columns=new TreeMap<Short,String>();IndexAccumulator(String n,boolean u,String t){name=n;unique=u;type=t;}}
}
