CREATE TABLE sql_data_source (
  id varchar(36) NOT NULL,
  product_id varchar(64) NOT NULL,
  name varchar(100) NOT NULL,
  engine varchar(20) NOT NULL,
  host varchar(255) NOT NULL,
  port int NOT NULL,
  username varchar(128) NOT NULL,
  password_ciphertext text NOT NULL,
  password_iv varchar(64) NOT NULL,
  key_version varchar(32) NOT NULL,
  default_database varchar(64) NULL,
  ssl_mode varchar(20) NOT NULL,
  connect_timeout_seconds int NOT NULL,
  properties_json json NOT NULL,
  description varchar(500) NULL,
  last_test_status varchar(20) NULL,
  last_test_at datetime(3) NULL,
  last_test_message varchar(500) NULL,
  version bigint NOT NULL,
  created_by varchar(64) NOT NULL,
  created_by_name varchar(100) NOT NULL,
  created_at datetime(3) NOT NULL,
  updated_by varchar(64) NOT NULL,
  updated_by_name varchar(100) NOT NULL,
  updated_at datetime(3) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_sql_ds_product_updated (product_id, updated_at DESC, id DESC),
  KEY idx_sql_ds_product_name (product_id, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
