CREATE TABLE sql_execution_history (
  id varchar(36) NOT NULL,
  user_id varchar(64) NOT NULL,
  username varchar(100) NOT NULL,
  product_id varchar(64) NOT NULL,
  data_source_id varchar(36) NOT NULL,
  data_source_name varchar(100) NOT NULL,
  database_name varchar(64) NULL,
  operation varchar(20) NOT NULL,
  statement_text mediumtext NOT NULL,
  statement_hash char(64) NOT NULL,
  statement_type varchar(32) NOT NULL,
  status varchar(20) NOT NULL,
  result_kind varchar(20) NULL,
  returned_rows bigint NULL,
  affected_rows bigint NULL,
  truncated boolean NOT NULL DEFAULT false,
  duration_ms bigint NULL,
  mysql_error_code int NULL,
  sql_state varchar(10) NULL,
  error_message varchar(1000) NULL,
  request_id varchar(64) NOT NULL,
  client_ip varchar(64) NULL,
  started_at datetime(3) NOT NULL,
  finished_at datetime(3) NULL,
  PRIMARY KEY (id),
  KEY idx_sql_history_user_started (user_id, started_at DESC, id DESC),
  KEY idx_sql_history_user_source_started (user_id, data_source_id, started_at DESC, id DESC),
  KEY idx_sql_history_user_status_started (user_id, status, started_at DESC, id DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
